/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tickserver;

import io.grpc.Server;
import io.grpc.ServerBuilder;
import java.io.IOException;

public class TickServerSimulator {

    public static void main(String[] args) throws IOException, InterruptedException {
        System.out.println("Starting Tickserver");

        Server server = ServerBuilder.forPort(50051)
            .addService(new TickServerImpl())
            .build();

        server.start();

        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            server.shutdown();
        }));

        server.awaitTermination();

        System.out.println("Tickserver stopped");

    }
}
