/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tickserver;

public class TickServerSimulator {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new TickServerSimulator().getGreeting());
    }
}
