/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tickserver;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class TickServerSimulatorTest {

  @Test
  void checkJavaVersion() {
    assertEquals(21, Runtime.version().feature(), "Java 21 needed but not found.");
  }
}
