/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tickserver;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TickServerSimulatorTest {

    @Test
    void appHasAGreeting() {
        TickServerSimulator classUnderTest = new TickServerSimulator();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void checkJavaVersion() {
        String javaVersionStr = System.getProperty("java.version");
        int dotIndex = javaVersionStr.indexOf(".");
        String majorVersionStr = dotIndex < 0 ? "UNKNOWN" : javaVersionStr.substring(0, dotIndex);

        assertEquals("16", majorVersionStr, "Testing with wrong java version");
    }
}
